#!/usr/bin/env python
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.support.select import Select
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.firefox.service import Service
from webdriver_manager.firefox import GeckoDriverManager
import time

def linksys():
    default_gateway = input("Please enter default gateway : ")
    ip_allocated = input("Please enter allocated ip : ")
    to_router = f"http://{default_gateway}"
    driver = webdriver.Firefox(service=Service(GeckoDriverManager().install()))
    driver.get(to_router)
    time.sleep(2)
    driver.maximize_window()
    time.sleep(2)

    try:
        driver.find_element(By.XPATH,"//div[@class = 'alert-message warning']/h4[contains(text(), 'No password set!')]")
        driver.find_element(By.CLASS_NAME, "cbi-button-apply").click()
        time.sleep(2)
    except:
        password = driver.find_element(By.NAME, "luci_password")
        password.send_keys("admin")
        password.send_keys(Keys.RETURN)
        time.sleep(2)

    # go to network page
    driver.find_element(By.XPATH, "//a[@href = '/cgi-bin/luci/admin/network' and contains(text(), 'Network')]").click()
    time.sleep(2)
    driver.find_element(By.XPATH, "//a[@href='/cgi-bin/luci/admin/network/wireless']").click()
    time.sleep(2)

    # WPA2 network
    driver.find_element(By.CLASS_NAME, "cbi-button-add").click()
    time.sleep(2)
    driver.find_element(By.CLASS_NAME, "cbi-tab-disabled").click()
    time.sleep(2)
    drop_down = driver.find_element(By.ID, "widget.cbid.wireless.radio0.country")
    time.sleep(2)
    select = Select(drop_down)
    select.select_by_value("IN")
    driver.find_element(By.ID, "modal_overlay").send_keys(Keys.PAGE_DOWN)
    time.sleep(3)
    ssid = driver.find_element(By.XPATH,"//div[@class ='cbi-value-field']/div[starts-with(@id, 'cbid.wireless.wifinet')]/input[@value ='OpenWrt']")
    ssid.clear()
    ssid.send_keys("WPA2")
    time.sleep(2)
    driver.find_element(By.XPATH, "//div[@class = 'cbi-value-field']/div/span[@class = 'more']").click()
    time.sleep(2)
    interface = driver.find_element(By.XPATH,"//div[@class = 'cbi-value-field cbi-dropdown-open']/div/ul/li[contains(@data-value, 'lan') and contains(@tabindex, '0')]/form/input[@type = 'checkbox']")
    action = ActionChains(driver)
    action.move_to_element(interface).click()
    time.sleep(2)
    action.perform()
    time.sleep(2)
    driver.find_element(By.XPATH, "//div/ul/li/a[contains(text(),'Wireless Security')]").click()
    time.sleep(2)
    wpa2 = Select(driver.find_element(By.XPATH,"//div[@class ='cbi-value-field']/div[starts-with(@id, 'cbid.wireless.wifinet') and contains(@id , 'encryption')]/select[starts-with(@id , 'widget.cbid.wireless.wifinet') and contains(@id , 'encryption')]"))
    wpa2.select_by_value("psk2")
    time.sleep(2)
    driver.find_element(By.XPATH,"//div[@class = 'control-group']/input[contains(@id, '_wpa_key') and @class='cbi-input-password']").send_keys("11112222")
    time.sleep(2)
    pmf_wpa2 = Select(driver.find_element(By.XPATH,"//div[@class = 'cbi-value-field']/div[contains(@id , 'ieee80211w') and starts-with(@id , 'cbid.wireless.wifinet')]/select[starts-with(@id , 'widget.cbid.wireless.wifinet') and contains(@id , 'ieee80211w')]"))
    pmf_wpa2.select_by_value("1")
    time.sleep(2)
    driver.find_element(By.XPATH, "//div[@id='modal_overlay']/div/div/button[contains(text(),'Save')]").click()
    print("Wpa2 profile created SSID : WPA2")

    # open
    time.sleep(4)
    driver.find_element(By.CLASS_NAME, "cbi-button-add").click()
    time.sleep(2)
    driver.find_element(By.CLASS_NAME, "cbi-tab-disabled").click()
    time.sleep(2)
    drop_down = driver.find_element(By.ID, "widget.cbid.wireless.radio0.country")
    time.sleep(2)
    select = Select(drop_down)
    select.select_by_value("IN")
    driver.find_element(By.ID, "modal_overlay").send_keys(Keys.PAGE_DOWN)
    time.sleep(5)
    ssid = driver.find_element(By.XPATH,"//div[@class ='cbi-value-field']/div[starts-with(@id, 'cbid.wireless.wifinet')]/input[@value ='OpenWrt']")
    ssid.clear()
    ssid.send_keys("Open_security")
    time.sleep(2)
    driver.find_element(By.XPATH, "//div[@class = 'cbi-value-field']/div/span[@class = 'more']").click()
    time.sleep(2)
    interface = driver.find_element(By.XPATH,"//div[@class = 'cbi-value-field cbi-dropdown-open']/div/ul/li[contains(@data-value, 'lan') and contains(@tabindex, '0')]/form/input[@type = 'checkbox']")
    action = ActionChains(driver)
    action.move_to_element(interface).click()
    action.perform()
    time.sleep(2)
    driver.find_element(By.XPATH, "//div/ul/li/a[contains(text(),'Wireless Security')]").click()
    time.sleep(2)
    wpa2 = Select(driver.find_element(By.XPATH,"//div[@class ='cbi-value-field']/div[starts-with(@id, 'cbid.wireless.wifinet') and contains(@id , 'encryption')]/select[starts-with(@id , 'widget.cbid.wireless.wifinet') and contains(@id , 'encryption')]"))
    wpa2.select_by_value("none")
    time.sleep(2)
    driver.find_element(By.XPATH, "//div[@id='modal_overlay']/div/div/button[contains(text(),'Save')]").click()
    print("Open network created SSID : Open_security")


    #Open DBCS hidden
    time.sleep(4)
    driver.find_element(By.CLASS_NAME, "cbi-button-add").click()
    time.sleep(2)
    driver.find_element(By.CLASS_NAME, "cbi-tab-disabled").click()
    time.sleep(2)
    drop_down = driver.find_element(By.ID, "widget.cbid.wireless.radio0.country")
    time.sleep(2)
    select = Select(drop_down)
    select.select_by_value("IN")
    driver.find_element(By.ID, "modal_overlay").send_keys(Keys.PAGE_DOWN)
    time.sleep(5)
    ssid = driver.find_element(By.XPATH,"//div[@class ='cbi-value-field']/div[starts-with(@id, 'cbid.wireless.wifinet')]/input[@value ='OpenWrt']")
    ssid.clear()
    ssid.send_keys("るるるる")
    time.sleep(2)
    driver.find_element(By.XPATH,"//div[@class = 'cbi-value-field']/div[starts-with(@id, 'cbid.wireless.wifinet') and contains(@id , 'hidden')]/input[@type = 'checkbox']").click()
    time.sleep(2)
    driver.find_element(By.XPATH, "//div[@class = 'cbi-value-field']/div/span[@class = 'more']").click()
    time.sleep(2)
    interface = driver.find_element(By.XPATH,"//div[@class = 'cbi-value-field cbi-dropdown-open']/div/ul/li[contains(@data-value, 'lan') and contains(@tabindex, '0')]/form/input[@type = 'checkbox']")
    action = ActionChains(driver)
    action.move_to_element(interface).click()
    action.perform()
    time.sleep(2)
    driver.find_element(By.XPATH, "//div/ul/li/a[contains(text(),'Wireless Security')]").click()
    time.sleep(2)
    wpa2 = Select(driver.find_element(By.XPATH,"//div[@class ='cbi-value-field']/div[starts-with(@id, 'cbid.wireless.wifinet') and contains(@id , 'encryption')]/select[starts-with(@id , 'widget.cbid.wireless.wifinet') and contains(@id , 'encryption')]"))
    wpa2.select_by_value("none")
    time.sleep(2)
    driver.find_element(By.XPATH, "//div[@id='modal_overlay']/div/div/button[contains(text(),'Save')]").click()
    print("Open DBCS Hidden network created SSID :るるるる")

    # WPA network
    time.sleep(4)
    driver.find_element(By.CLASS_NAME, "cbi-button-add").click()
    time.sleep(2)
    driver.find_element(By.CLASS_NAME, "cbi-tab-disabled").click()
    time.sleep(2)
    drop_down = driver.find_element(By.ID, "widget.cbid.wireless.radio0.country")
    time.sleep(2)
    select = Select(drop_down)
    select.select_by_value("IN")
    driver.find_element(By.ID, "modal_overlay").send_keys(Keys.PAGE_DOWN)
    time.sleep(5)
    ssid = driver.find_element(By.XPATH,"//div[@class ='cbi-value-field']/div[starts-with(@id, 'cbid.wireless.wifinet')]/input[@value ='OpenWrt']")
    ssid.clear()
    ssid.send_keys("WPA")
    time.sleep(2)
    driver.find_element(By.XPATH, "//div[@class = 'cbi-value-field']/div/span[@class = 'more']").click()
    time.sleep(2)
    interface = driver.find_element(By.XPATH,"//div[@class = 'cbi-value-field cbi-dropdown-open']/div/ul/li[contains(@data-value, 'lan') and contains(@tabindex, '0')]/form/input[@type = 'checkbox']")
    action = ActionChains(driver)
    action.move_to_element(interface).click()
    action.perform()
    time.sleep(2)
    driver.find_element(By.XPATH, "//div/ul/li/a[contains(text(),'Wireless Security')]").click()
    time.sleep(2)
    wpa2 = Select(driver.find_element(By.XPATH, "//div[@class ='cbi-value-field']/div[starts-with(@id, 'cbid.wireless.wifinet') and contains(@id , 'encryption')]/select[starts-with(@id , 'widget.cbid.wireless.wifinet') and contains(@id , 'encryption')]"))
    wpa2.select_by_value("psk")
    time.sleep(2)
    driver.find_element(By.XPATH, "//div[@class = 'control-group']/input[contains(@id, '_wpa_key') and @class='cbi-input-password']").send_keys("11112222")
    time.sleep(2)
    driver.find_element(By.XPATH, "//div[@id='modal_overlay']/div/div/button[contains(text(),'Save')]").click()
    print("WPA profile created SSID : WPA")

    # EAP network

    time.sleep(4)
    driver.find_element(By.CLASS_NAME, "cbi-button-add").click()
    time.sleep(2)
    driver.find_element(By.CLASS_NAME, "cbi-tab-disabled").click()
    time.sleep(2)
    drop_down = driver.find_element(By.ID, "widget.cbid.wireless.radio0.country")
    time.sleep(2)
    select = Select(drop_down)
    select.select_by_value("IN")
    driver.find_element(By.ID, "modal_overlay").send_keys(Keys.PAGE_DOWN)
    time.sleep(5)
    ssid = driver.find_element(By.XPATH, "//div[@class ='cbi-value-field']/div[starts-with(@id, 'cbid.wireless.wifinet')]/input[@value ='OpenWrt']")
    ssid.clear()
    ssid.send_keys("WPA2-EAP")
    time.sleep(2)
    driver.find_element(By.XPATH, "//div[@class = 'cbi-value-field']/div/span[@class = 'more']").click()
    time.sleep(2)
    interface = driver.find_element(By.XPATH, "//div[@class = 'cbi-value-field cbi-dropdown-open']/div/ul/li[contains(@data-value, 'lan') and contains(@tabindex, '0')]/form/input[@type = 'checkbox']")
    action = ActionChains(driver)
    action.move_to_element(interface).click()
    action.perform()
    driver.find_element(By.XPATH, "//div/ul/li/a[contains(text(),'Wireless Security')]").click()
    time.sleep(2)
    wpa2 = Select(driver.find_element(By.XPATH, "//div[@class ='cbi-value-field']/div[starts-with(@id, 'cbid.wireless.wifinet') and contains(@id , 'encryption')]/select[starts-with(@id , 'widget.cbid.wireless.wifinet') and contains(@id , 'encryption')]"))
    wpa2.select_by_value("wpa2")
    time.sleep(2)
    driver.find_element(By.XPATH, "//div[@class ='cbi-value-field']/div[starts-with(@id, 'cbid.wireless.wifinet') and contains(@id , 'auth_server')]/input[starts-with(@id , 'widget.cbid.wireless.wifinet') and contains(@id , 'auth_server')]").send_keys(ip_allocated)
    time.sleep(2)
    driver.find_element(By.XPATH, "//div[@class ='cbi-value-field']/div[starts-with(@id, 'cbid.wireless.wifinet') and contains(@id , 'auth_port')]/input[starts-with(@id , 'widget.cbid.wireless.wifinet') and contains(@id , 'auth_port')]").send_keys("1812")
    time.sleep(2)
    driver.find_element(By.XPATH, "//div[@class ='cbi-value-field']/div[starts-with(@id, 'cbid.wireless.wifinet') and contains (@id, 'auth_secret')]/div/input[starts-with(@id, 'widget.cbid.wireless.wifinet') and contains(@id, 'auth_secret')]").send_keys("1234567890")
    time.sleep(2)
    pmf = Select(driver.find_element(By.XPATH, "//div[@class = 'cbi-value-field']/div[contains(@id , 'ieee80211w') and starts-with(@id , 'cbid.wireless.wifinet')]/select[starts-with(@id , 'widget.cbid.wireless.wifinet') and contains(@id , 'ieee80211w')]"))
    pmf.select_by_value("1")
    time.sleep(2)
    driver.find_element(By.XPATH, "//div[@id='modal_overlay']/div/div/button[contains(text(),'Save')]").click()
    print("EAP profile created SSID : WPA2-EAP")

    # Transistion network
    time.sleep(4)
    driver.find_element(By.XPATH,"//tr[@id = 'cbi-wireless-radio1']/td[@class = 'td middle cbi-section-actions']/div/button[starts-with(@class, 'cbi-button') and contains(@class, 'cbi-button-add') and contains(text(), 'Add')]").click()
    time.sleep(2)
    driver.find_element(By.XPATH,"//div[@class = 'cbi-section']/ul/li[@class = 'cbi-tab']/a[contains(text(), 'General Setup')]").click()
    time.sleep(2)
    channel = Select(driver.find_element(By.XPATH, "//div[@class = 'cbi-value-field']/div/label/select[@class = 'channel']"))
    channel.select_by_value("60")
    time.sleep(2)
    driver.find_element(By.CLASS_NAME, "cbi-tab-disabled").click()
    time.sleep(2)
    drop_down = driver.find_element(By.ID, "widget.cbid.wireless.radio1.country")
    time.sleep(2)
    select = Select(drop_down)
    select.select_by_value("IN")
    driver.find_element(By.ID, "modal_overlay").send_keys(Keys.PAGE_DOWN)
    time.sleep(5)
    ssid = driver.find_element(By.XPATH,"//div[@class ='cbi-value-field']/div[starts-with(@id, 'cbid.wireless.wifinet')]/input[@value ='OpenWrt']")
    ssid.clear()
    ssid.send_keys("WPA2/WPA3")
    time.sleep(2)
    driver.find_element(By.XPATH, "//div[@class = 'cbi-value-field']/div/span[@class = 'more']").click()
    time.sleep(2)
    interface = driver.find_element(By.XPATH,"//div[@class = 'cbi-value-field cbi-dropdown-open']/div/ul/li[contains(@data-value, 'lan') and contains(@tabindex, '0')]/form/input[@type = 'checkbox']")
    action = ActionChains(driver)
    action.move_to_element(interface).click()
    action.perform()
    driver.find_element(By.XPATH, "//div/ul/li/a[contains(text(),'Wireless Security')]").click()
    time.sleep(2)
    wpa2 = Select(driver.find_element(By.XPATH,"//div[@class ='cbi-value-field']/div[starts-with(@id, 'cbid.wireless.wifinet') and contains(@id , 'encryption')]/select[starts-with(@id , 'widget.cbid.wireless.wifinet') and contains(@id , 'encryption')]"))
    wpa2.select_by_value("sae-mixed")
    time.sleep(2)
    driver.find_element(By.XPATH,"//div[@class = 'control-group']/input[contains(@id, '_wpa_key') and @class='cbi-input-password']").send_keys("11112222")
    pmf_wpa2 = Select(driver.find_element(By.XPATH,"//div[@class = 'cbi-value-field']/div[contains(@id , 'ieee80211w') and starts-with(@id , 'cbid.wireless.wifinet')]/select[starts-with(@id , 'widget.cbid.wireless.wifinet') and contains(@id , 'ieee80211w')]"))
    pmf_wpa2.select_by_value("1")
    time.sleep(2)
    driver.find_element(By.XPATH, "//div[@id='modal_overlay']/div/div/button[contains(text(),'Save')]").click()
    print("WPA2/WPA3 profile created SSID : WPA2/WPA3")

    # 32 characters
    time.sleep(4)
    driver.find_element(By.XPATH, "//tr[@id = 'cbi-wireless-radio1']/td[@class = 'td middle cbi-section-actions']/div/button[starts-with(@class, 'cbi-button') and contains(@class, 'cbi-button-add') and contains(text(), 'Add')]").click()
    time.sleep(2)
    driver.find_element(By.XPATH,"//div[@class = 'cbi-section']/ul/li[@class = 'cbi-tab']/a[contains(text(), 'General Setup')]").click()
    time.sleep(2)
    channel = Select(driver.find_element(By.XPATH, "//div[@class = 'cbi-value-field']/div/label/select[@class = 'channel']"))
    channel.select_by_value("60")
    time.sleep(2)
    driver.find_element(By.CLASS_NAME, "cbi-tab-disabled").click()
    time.sleep(2)
    drop_down = driver.find_element(By.ID, "widget.cbid.wireless.radio1.country")
    time.sleep(2)
    select = Select(drop_down)
    select.select_by_value("IN")
    driver.find_element(By.ID, "modal_overlay").send_keys(Keys.PAGE_DOWN)
    time.sleep(3)
    ssid = driver.find_element(By.XPATH, "//div[@class ='cbi-value-field']/div[starts-with(@id, 'cbid.wireless.wifinet')]/input[@value ='OpenWrt']")
    ssid.clear()
    ssid.send_keys("abcdefghijklmnopqrstuvwxyz123456")
    time.sleep(2)
    driver.find_element(By.XPATH, "//div[@class = 'cbi-value-field']/div/span[@class = 'more']").click()
    time.sleep(2)
    interface = driver.find_element(By.XPATH, "//div[@class = 'cbi-value-field cbi-dropdown-open']/div/ul/li[contains(@data-value, 'lan') and contains(@tabindex, '0')]/form/input[@type = 'checkbox']")
    action = ActionChains(driver)
    action.move_to_element(interface).click()
    action.perform()
    driver.find_element(By.XPATH, "//div/ul/li/a[contains(text(),'Wireless Security')]").click()
    time.sleep(2)
    wpa2 = Select(driver.find_element(By.XPATH, "//div[@class ='cbi-value-field']/div[starts-with(@id, 'cbid.wireless.wifinet') and contains(@id , 'encryption')]/select[starts-with(@id , 'widget.cbid.wireless.wifinet') and contains(@id , 'encryption')]"))
    wpa2.select_by_value("psk")
    time.sleep(2)
    driver.find_element(By.XPATH, "//div[@class = 'control-group']/input[contains(@id, '_wpa_key') and @class='cbi-input-password']").send_keys("11112222")
    time.sleep(2)
    driver.find_element(By.XPATH, "//div[@id='modal_overlay']/div/div/button[contains(text(),'Save')]").click()
    print("32 characters profile created SSID : abcdefghijklmnopqrstuvwxyz123456")

    # emoji profile
    time.sleep(4)
    driver.find_element(By.XPATH, "//tr[@id = 'cbi-wireless-radio1']/td[@class = 'td middle cbi-section-actions']/div/button[starts-with(@class, 'cbi-button') and contains(@class, 'cbi-button-add') and contains(text(), 'Add')]").click()
    time.sleep(2)
    driver.find_element(By.CLASS_NAME, "cbi-tab-disabled").click()
    time.sleep(2)
    drop_down = driver.find_element(By.ID, "widget.cbid.wireless.radio1.country")
    time.sleep(2)
    select = Select(drop_down)
    select.select_by_value("IN")
    driver.find_element(By.ID, "modal_overlay").send_keys(Keys.PAGE_DOWN)
    time.sleep(3)
    ssid = driver.find_element(By.XPATH, "//div[@class ='cbi-value-field']/div[starts-with(@id, 'cbid.wireless.wifinet')]/input[@value ='OpenWrt']")
    ssid.clear()
    ssid.send_keys("😄😄😄😄")
    time.sleep(2)
    driver.find_element(By.XPATH, "//div[@class = 'cbi-value-field']/div/span[@class = 'more']").click()
    time.sleep(2)
    interface = driver.find_element(By.XPATH, "//div[@class = 'cbi-value-field cbi-dropdown-open']/div/ul/li[contains(@data-value, 'lan') and contains(@tabindex, '0')]/form/input[@type = 'checkbox']")
    action = ActionChains(driver)
    action.move_to_element(interface).click()
    action.perform()
    driver.find_element(By.XPATH, "//div/ul/li/a[contains(text(),'Wireless Security')]").click()
    time.sleep(2)
    wpa2 = Select(driver.find_element(By.XPATH, "//div[@class ='cbi-value-field']/div[starts-with(@id, 'cbid.wireless.wifinet') and contains(@id , 'encryption')]/select[starts-with(@id , 'widget.cbid.wireless.wifinet') and contains(@id , 'encryption')]"))
    wpa2.select_by_value("psk2")
    time.sleep(2)
    driver.find_element(By.XPATH, "//div[@class = 'control-group']/input[contains(@id, '_wpa_key') and @class='cbi-input-password']").send_keys("11112222")
    pmf_wpa2 = Select(driver.find_element(By.XPATH, "//div[@class = 'cbi-value-field']/div[contains(@id , 'ieee80211w') and starts-with(@id , 'cbid.wireless.wifinet')]/select[starts-with(@id , 'widget.cbid.wireless.wifinet') and contains(@id , 'ieee80211w')]"))
    pmf_wpa2.select_by_value("1")
    time.sleep(2)
    driver.find_element(By.XPATH, "//div[@id='modal_overlay']/div/div/button[contains(text(),'Save')]").click()
    print("Emoji profile created SSID : 😄😄😄😄\n")
    print("Note : WEP security is not available in this router")
    # final save and apply
    time.sleep(5)
    driver.find_element(By.XPATH, "//div[@id='view']/div/div/ul/li[contains(text(),'Save & Apply')]").click()
    time.sleep(2)


def tp_link():

    default_gateway = input("Please enter default gateway : ")
    ip_allocated = input("Please enter allocated ip : ")
    to_router = f"http://{default_gateway}"
    driver = webdriver.Firefox(service=Service(GeckoDriverManager().install()))
    driver.get(to_router)
    time.sleep(2)
    driver.maximize_window()
    time.sleep(2)
    try:
        driver.find_element(By.XPATH, "//div[@class = 'alert-message warning']/h4[contains(text(), 'No password set!')]")
        driver.find_element(By.CLASS_NAME, "cbi-button-apply").click()
        time.sleep(2)
    except:
        password = driver.find_element(By.NAME, "luci_password")
        password.send_keys('admin@123')
        password.send_keys(Keys.RETURN)
        time.sleep(2)


    # go to network page
    driver.find_element(By.XPATH, "//ul[@id = 'topmenu']/li/a[@class= 'menu' and contains(text(),'Network')]").click()
    time.sleep(2)
    driver.find_element(By.XPATH, "//a[@href='/cgi-bin/luci/admin/network/wireless']").click()
    time.sleep(2)

    # WEP
    time.sleep(2)
    driver.find_element(By.CLASS_NAME, "cbi-button-add").click()
    time.sleep(2)
    driver.find_element(By.CLASS_NAME, "cbi-tab-disabled").click()
    drop_down = driver.find_element(By.ID, "widget.cbid.wireless.radio0.country")
    time.sleep(2)
    select = Select(drop_down)
    select.select_by_value("")
    driver.find_element(By.ID, "modal_overlay").send_keys(Keys.PAGE_DOWN)
    time.sleep(3)
    ssid = driver.find_element(By.XPATH, "//div[@class ='cbi-value-field']/div[starts-with(@id, 'cbid.wireless.wifinet')]/input[@value ='OpenWrt']")
    ssid.clear()
    ssid.send_keys("WEP")
    time.sleep(2)
    driver.find_element(By.XPATH, "//div[@class = 'cbi-value-field']/div/span[@class = 'more']").click()
    time.sleep(2)
    interface = driver.find_element(By.XPATH, "//div[@class = 'cbi-value-field cbi-dropdown-open']/div/ul/li[contains(@data-value, 'lan') and contains(@tabindex, '0')]/form/input[@type = 'checkbox']")
    action = ActionChains(driver)
    action.move_to_element(interface).click()
    time.sleep(2)
    action.perform()
    time.sleep(2)
    driver.find_element(By.XPATH, "//div/ul/li/a[contains(text(),'Wireless Security')]").click()
    time.sleep(2)
    wpa2 = Select(driver.find_element(By.XPATH, "//div[@class ='cbi-value-field']/div[starts-with(@id, 'cbid.wireless.wifinet') and contains(@id , 'encryption')]/select[starts-with(@id , 'widget.cbid.wireless.wifinet') and contains(@id , 'encryption')]"))
    wpa2.select_by_value("wep-shared")
    time.sleep(2)
    parent = driver.find_element(By.XPATH, "//div[@class= 'cbi-value-field']/div[starts-with(@id, 'cbid.wireless.wifinet') and contains(@id, '2.key1')]/input[starts-with(@class , 'cbi-input-password')]")
    parent.find_element(By.XPATH, "//div[@class= 'cbi-value-field']/div[starts-with(@id, 'cbid.wireless.wifinet') and contains(@id, '2.key1')]/input[starts-with(@class , 'cbi-input-password')]").send_keys('12345')
    time.sleep(2)
    driver.find_element(By.XPATH, "//div[@id='modal_overlay']/div/div/button[contains(text(),'Save')]").click()
    print("Wep profile created SSID: WEP")

    # transition network
    time.sleep(3)
    driver.find_element(By.CLASS_NAME, "cbi-button-add").click()
    time.sleep(2)
    driver.find_element(By.CLASS_NAME, "cbi-tab-disabled").click()
    drop_down = driver.find_element(By.ID, "widget.cbid.wireless.radio0.country")
    time.sleep(2)
    select = Select(drop_down)
    select.select_by_value("")
    driver.find_element(By.ID, "modal_overlay").send_keys(Keys.PAGE_DOWN)
    time.sleep(3)
    ssid = driver.find_element(By.XPATH,"//div[@class ='cbi-value-field']/div[starts-with(@id, 'cbid.wireless.wifinet')]/input[@value ='OpenWrt']")
    ssid.clear()
    ssid.send_keys("WPA2/WPA3")
    time.sleep(2)
    driver.find_element(By.XPATH, "//div[@class = 'cbi-value-field']/div/span[@class = 'more']").click()
    time.sleep(2)
    interface = driver.find_element(By.XPATH,"//div[@class = 'cbi-value-field cbi-dropdown-open']/div/ul/li[contains(@data-value, 'lan') and contains(@tabindex, '0')]/form/input[@type = 'checkbox']")
    action = ActionChains(driver)
    action.move_to_element(interface).click()
    time.sleep(2)
    action.perform()
    time.sleep(2)
    driver.find_element(By.XPATH, "//div/ul/li/a[contains(text(),'Wireless Security')]").click()
    time.sleep(2)
    wpa2 = Select(driver.find_element(By.XPATH,"//div[@class ='cbi-value-field']/div[starts-with(@id, 'cbid.wireless.wifinet') and contains(@id , 'encryption')]/select[starts-with(@id , 'widget.cbid.wireless.wifinet') and contains(@id , 'encryption')]"))
    wpa2.select_by_value("sae-mixed")
    time.sleep(2)
    parent = driver.find_element(By.XPATH,"//div[@class= 'cbi-value-field']/div[starts-with(@id, 'cbid.wireless.wifinet') and contains(@id, '_wpa_key')]/input")
    parent.find_element(By.XPATH,"//input[starts-with(@id, 'widget.cbid.wireless.wifinet') and contains(@id, '_wpa_key') and contains(@class, 'cbi-input-password')]").send_keys('11112222')
    time.sleep(2)
    pmf_wpa2 = Select(driver.find_element(By.XPATH,"//div[@class = 'cbi-value-field']/div[contains(@id , 'ieee80211w') and starts-with(@id , 'cbid.wireless.wifinet')]/select[starts-with(@id , 'widget.cbid.wireless.wifinet') and contains(@id , 'ieee80211w')]"))
    pmf_wpa2.select_by_value("1")
    time.sleep(2)
    driver.find_element(By.XPATH, "//div[@id='modal_overlay']/div/div/button[contains(text(),'Save')]").click()
    print("Wpa2/Wpa3 profile created SSID:WPA2/WPA3")


    #32 characters
    time.sleep(3)
    driver.find_element(By.CLASS_NAME, "cbi-button-add").click()
    time.sleep(2)
    driver.find_element(By.CLASS_NAME, "cbi-tab-disabled").click()
    drop_down = driver.find_element(By.ID, "widget.cbid.wireless.radio0.country")
    time.sleep(2)
    select = Select(drop_down)
    select.select_by_value("")
    driver.find_element(By.ID, "modal_overlay").send_keys(Keys.PAGE_DOWN)
    time.sleep(3)
    ssid = driver.find_element(By.XPATH,"//div[@class ='cbi-value-field']/div[starts-with(@id, 'cbid.wireless.wifinet')]/input[@value ='OpenWrt']")
    ssid.clear()
    ssid.send_keys("abcdefghijklmnopqrstuvwxyz123456")
    time.sleep(2)
    driver.find_element(By.XPATH, "//div[@class = 'cbi-value-field']/div/span[@class = 'more']").click()
    time.sleep(2)
    interface = driver.find_element(By.XPATH,"//div[@class = 'cbi-value-field cbi-dropdown-open']/div/ul/li[contains(@data-value, 'lan') and contains(@tabindex, '0')]/form/input[@type = 'checkbox']")
    action = ActionChains(driver)
    action.move_to_element(interface).click()
    time.sleep(2)
    action.perform()
    time.sleep(2)
    driver.find_element(By.XPATH, "//div/ul/li/a[contains(text(),'Wireless Security')]").click()
    time.sleep(2)
    wpa2 = Select(driver.find_element(By.XPATH,"//div[@class ='cbi-value-field']/div[starts-with(@id, 'cbid.wireless.wifinet') and contains(@id , 'encryption')]/select[starts-with(@id , 'widget.cbid.wireless.wifinet') and contains(@id , 'encryption')]"))
    wpa2.select_by_value("psk")
    time.sleep(2)
    parent = driver.find_element(By.XPATH,"//div[@class= 'cbi-value-field']/div[starts-with(@id, 'cbid.wireless.wifinet') and contains(@id, '_wpa_key')]/input")
    parent.find_element(By.XPATH,"//input[starts-with(@id, 'widget.cbid.wireless.wifinet') and contains(@id, '_wpa_key') and contains(@class, 'cbi-input-password')]").send_keys('11112222')
    time.sleep(2)
    driver.find_element(By.XPATH, "//div[@id='modal_overlay']/div/div/button[contains(text(),'Save')]").click()
    print("Wpa2/Wpa3 profile created SSID:abcdefghijklmnopqrstuvwxyz123456")


    #Open
    time.sleep(3)
    driver.find_element(By.CLASS_NAME, "cbi-button-add").click()
    time.sleep(2)
    driver.find_element(By.CLASS_NAME, "cbi-tab-disabled").click()
    drop_down = driver.find_element(By.ID, "widget.cbid.wireless.radio0.country")
    time.sleep(2)
    select = Select(drop_down)
    select.select_by_value("")
    driver.find_element(By.ID, "modal_overlay").send_keys(Keys.PAGE_DOWN)
    time.sleep(3)
    ssid = driver.find_element(By.XPATH, "//div[@class ='cbi-value-field']/div[starts-with(@id, 'cbid.wireless.wifinet')]/input[@value ='OpenWrt']")
    ssid.clear()
    ssid.send_keys("Open")
    time.sleep(2)
    driver.find_element(By.XPATH, "//div[@class = 'cbi-value-field']/div/span[@class = 'more']").click()
    time.sleep(2)
    interface = driver.find_element(By.XPATH, "//div[@class = 'cbi-value-field cbi-dropdown-open']/div/ul/li[contains(@data-value, 'lan') and contains(@tabindex, '0')]/form/input[@type = 'checkbox']")
    action = ActionChains(driver)
    action.move_to_element(interface).click()
    time.sleep(2)
    action.perform()
    time.sleep(2)
    driver.find_element(By.XPATH, "//div/ul/li/a[contains(text(),'Wireless Security')]").click()
    time.sleep(2)
    wpa2 = Select(driver.find_element(By.XPATH, "//div[@class ='cbi-value-field']/div[starts-with(@id, 'cbid.wireless.wifinet') and contains(@id , 'encryption')]/select[starts-with(@id , 'widget.cbid.wireless.wifinet') and contains(@id , 'encryption')]"))
    wpa2.select_by_value("none")
    time.sleep(2)
    driver.find_element(By.XPATH, "//div[@id='modal_overlay']/div/div/button[contains(text(),'Save')]").click()
    print("Open profile created SSID: Open")

    #WPA network
    time.sleep(3)
    driver.find_element(By.XPATH,"//div[@id='cbi-wireless-radio1']/div/div/button[contains(@class, 'cbi-button-add')]").click()
    time.sleep(2)
    driver.find_element(By.CLASS_NAME, "cbi-tab-disabled").click()
    drop_down = driver.find_element(By.ID, "widget.cbid.wireless.radio1.country")
    time.sleep(2)
    select = Select(drop_down)
    select.select_by_value("")
    driver.find_element(By.ID, "modal_overlay").send_keys(Keys.PAGE_DOWN)
    time.sleep(3)
    ssid = driver.find_element(By.XPATH,"//div[@class ='cbi-value-field']/div[starts-with(@id, 'cbid.wireless.wifinet')]/input[@value ='OpenWrt']")
    ssid.clear()
    ssid.send_keys("WPA")
    time.sleep(2)
    driver.find_element(By.XPATH, "//div[@class = 'cbi-value-field']/div/span[@class = 'more']").click()
    time.sleep(2)
    interface = driver.find_element(By.XPATH,"//div[@class = 'cbi-value-field cbi-dropdown-open']/div/ul/li[contains(@data-value, 'lan') and contains(@tabindex, '0')]/form/input[@type = 'checkbox']")
    action = ActionChains(driver)
    action.move_to_element(interface).click()
    time.sleep(2)
    action.perform()
    time.sleep(2)
    driver.find_element(By.XPATH, "//div/ul/li/a[contains(text(),'Wireless Security')]").click()
    time.sleep(2)
    wpa2 = Select(driver.find_element(By.XPATH,"//div[@class ='cbi-value-field']/div[starts-with(@id, 'cbid.wireless.wifinet') and contains(@id , 'encryption')]/select[starts-with(@id , 'widget.cbid.wireless.wifinet') and contains(@id , 'encryption')]"))
    wpa2.select_by_value("psk")
    time.sleep(2)
    parent = driver.find_element(By.XPATH,"//div[@class= 'cbi-value-field']/div[starts-with(@id, 'cbid.wireless.wifinet') and contains(@id, '_wpa_key')]/input")
    parent.find_element(By.XPATH,"//input[starts-with(@id, 'widget.cbid.wireless.wifinet') and contains(@id, '_wpa_key') and contains(@class, 'cbi-input-password')]").send_keys('11112222')
    time.sleep(2)
    driver.find_element(By.XPATH, "//div[@id='modal_overlay']/div/div/button[contains(text(),'Save')]").click()
    print("Wpa profile created SSID: WPA")

#WPA2 network

    time.sleep(3)
    driver.find_element(By.XPATH,"//div[@id='cbi-wireless-radio1']/div/div/button[contains(@class, 'cbi-button-add')]").click()
    time.sleep(2)
    driver.find_element(By.CLASS_NAME, "cbi-tab-disabled").click()
    drop_down = driver.find_element(By.ID, "widget.cbid.wireless.radio1.country")
    time.sleep(2)
    select = Select(drop_down)
    select.select_by_value("")
    driver.find_element(By.ID, "modal_overlay").send_keys(Keys.PAGE_DOWN)
    time.sleep(3)
    ssid = driver.find_element(By.XPATH,"//div[@class ='cbi-value-field']/div[starts-with(@id, 'cbid.wireless.wifinet')]/input[@value ='OpenWrt']")
    ssid.clear()
    ssid.send_keys("WPA2")
    time.sleep(2)
    driver.find_element(By.XPATH, "//div[@class = 'cbi-value-field']/div/span[@class = 'more']").click()
    time.sleep(2)
    interface = driver.find_element(By.XPATH,"//div[@class = 'cbi-value-field cbi-dropdown-open']/div/ul/li[contains(@data-value, 'lan') and contains(@tabindex, '0')]/form/input[@type = 'checkbox']")
    action = ActionChains(driver)
    action.move_to_element(interface).click()
    time.sleep(2)
    action.perform()
    time.sleep(2)
    driver.find_element(By.XPATH, "//div/ul/li/a[contains(text(),'Wireless Security')]").click()
    time.sleep(2)
    wpa2 = Select(driver.find_element(By.XPATH,"//div[@class ='cbi-value-field']/div[starts-with(@id, 'cbid.wireless.wifinet') and contains(@id , 'encryption')]/select[starts-with(@id , 'widget.cbid.wireless.wifinet') and contains(@id , 'encryption')]"))
    wpa2.select_by_value("psk2")
    time.sleep(2)
    parent = driver.find_element(By.XPATH,"//div[@class= 'cbi-value-field']/div[starts-with(@id, 'cbid.wireless.wifinet') and contains(@id, '_wpa_key')]/input")
    parent.find_element(By.XPATH,"//input[starts-with(@id, 'widget.cbid.wireless.wifinet') and contains(@id, '_wpa_key') and contains(@class, 'cbi-input-password')]").send_keys('11112222')
    time.sleep(2)
    pmf_wpa2 = Select(driver.find_element(By.XPATH,"//div[@class = 'cbi-value-field']/div[contains(@id , 'ieee80211w') and starts-with(@id , 'cbid.wireless.wifinet')]/select[starts-with(@id , 'widget.cbid.wireless.wifinet') and contains(@id , 'ieee80211w')]"))
    pmf_wpa2.select_by_value("1")
    time.sleep(2)
    driver.find_element(By.XPATH, "//div[@id='modal_overlay']/div/div/button[contains(text(),'Save')]").click()
    print("Wpa2 profile created SSID: WPA2")

    # Open DBCS hidden
    time.sleep(3)
    driver.find_element(By.XPATH, "//div[@id='cbi-wireless-radio1']/div/div/button[contains(@class, 'cbi-button-add')]").click()
    time.sleep(2)
    driver.find_element(By.CLASS_NAME, "cbi-tab-disabled").click()
    drop_down = driver.find_element(By.ID, "widget.cbid.wireless.radio1.country")
    time.sleep(2)
    select = Select(drop_down)
    select.select_by_value("")
    driver.find_element(By.ID, "modal_overlay").send_keys(Keys.PAGE_DOWN)
    time.sleep(3)
    ssid = driver.find_element(By.XPATH, "//div[@class ='cbi-value-field']/div[starts-with(@id, 'cbid.wireless.wifinet')]/input[@value ='OpenWrt']")
    ssid.clear()
    ssid.send_keys("るるるる")
    time.sleep(2)
    driver.find_element(By.XPATH,"//div[@class = 'cbi-value-field']/div[starts-with(@id, 'cbid.wireless.wifinet') and contains(@id, 'hidden')]/input[@type = 'checkbox']").click()
    time.sleep(2)
    driver.find_element(By.XPATH, "//div[@class = 'cbi-value-field']/div/span[@class = 'more']").click()
    time.sleep(2)
    interface = driver.find_element(By.XPATH, "//div[@class = 'cbi-value-field cbi-dropdown-open']/div/ul/li[contains(@data-value, 'lan') and contains(@tabindex, '0')]/form/input[@type = 'checkbox']")
    action = ActionChains(driver)
    action.move_to_element(interface).click()
    time.sleep(2)
    action.perform()
    time.sleep(2)
    driver.find_element(By.XPATH, "//div/ul/li/a[contains(text(),'Wireless Security')]").click()
    time.sleep(2)
    wpa2 = Select(driver.find_element(By.XPATH, "//div[@class ='cbi-value-field']/div[starts-with(@id, 'cbid.wireless.wifinet') and contains(@id , 'encryption')]/select[starts-with(@id , 'widget.cbid.wireless.wifinet') and contains(@id , 'encryption')]"))
    wpa2.select_by_value("none")
    time.sleep(2)
    driver.find_element(By.XPATH, "//div[@id='modal_overlay']/div/div/button[contains(text(),'Save')]").click()
    print("Open DBCS Hidden network created SSID :るるるる")


    # EAP network


    time.sleep(3)
    driver.find_element(By.XPATH,"//div[@id='cbi-wireless-radio1']/div/div/button[contains(@class, 'cbi-button-add')]").click()
    time.sleep(2)
    driver.find_element(By.CLASS_NAME, "cbi-tab-disabled").click()
    drop_down = driver.find_element(By.ID, "widget.cbid.wireless.radio1.country")
    time.sleep(2)
    select = Select(drop_down)
    select.select_by_value("")
    driver.find_element(By.ID, "modal_overlay").send_keys(Keys.PAGE_DOWN)
    time.sleep(3)
    ssid = driver.find_element(By.XPATH,"//div[@class ='cbi-value-field']/div[starts-with(@id, 'cbid.wireless.wifinet')]/input[@value ='OpenWrt']")
    ssid.clear()
    ssid.send_keys("WPA2_EAP")
    time.sleep(2)
    driver.find_element(By.XPATH, "//div[@class = 'cbi-value-field']/div/span[@class = 'more']").click()
    time.sleep(2)
    interface = driver.find_element(By.XPATH,"//div[@class = 'cbi-value-field cbi-dropdown-open']/div/ul/li[contains(@data-value, 'lan') and contains(@tabindex, '0')]/form/input[@type = 'checkbox']")
    action = ActionChains(driver)
    action.move_to_element(interface).click()
    time.sleep(2)
    action.perform()
    time.sleep(2)
    driver.find_element(By.XPATH, "//div/ul/li/a[contains(text(),'Wireless Security')]").click()
    time.sleep(2)
    wpa2 = Select(driver.find_element(By.XPATH,"//div[@class ='cbi-value-field']/div[starts-with(@id, 'cbid.wireless.wifinet') and contains(@id , 'encryption')]/select[starts-with(@id , 'widget.cbid.wireless.wifinet') and contains(@id , 'encryption')]"))
    wpa2.select_by_value("wpa2")
    time.sleep(2)
    driver.find_element(By.XPATH,"//div[@class = 'cbi-value-field']/div[starts-with(@id, 'cbid.wireless.wifinet') and contains(@id, 'auth_server')]/input[contains(@id, 'auth_server')]").send_keys(ip_allocated)
    time.sleep(2)
    driver.find_element(By.XPATH,"//div[@class = 'cbi-value-field']/div[starts-with(@id, 'cbid.wireless.wifinet') and contains(@id, 'auth_port')]/input[contains(@id, 'auth_port')]").send_keys('1812')
    time.sleep(2)
    parent = driver.find_element(By.XPATH,"//div[@class= 'cbi-value-field']/div[starts-with(@id, 'cbid.wireless.wifinet') and contains(@id, 'auth_secret')]/input[contains(@id, 'auth_secret')]")
    parent.send_keys('1234567890')
    time.sleep(2)
    pmf_wpa2 = Select(driver.find_element(By.XPATH,"//div[@class = 'cbi-value-field']/div[contains(@id , 'ieee80211w') and starts-with(@id , 'cbid.wireless.wifinet')]/select[starts-with(@id , 'widget.cbid.wireless.wifinet') and contains(@id , 'ieee80211w')]"))
    pmf_wpa2.select_by_value("1")
    time.sleep(2)
    driver.find_element(By.XPATH, "//div[@id='modal_overlay']/div/div/button[contains(text(),'Save')]").click()
    print("EAP profile created SSID: WPA2_EAP")

    # emoji profile
    time.sleep(3)
    driver.find_element(By.XPATH, "//div[@id='cbi-wireless-radio1']/div/div/button[contains(@class, 'cbi-button-add')]").click()
    time.sleep(2)
    driver.find_element(By.CLASS_NAME, "cbi-tab-disabled").click()
    drop_down = driver.find_element(By.ID, "widget.cbid.wireless.radio1.country")
    time.sleep(2)
    select = Select(drop_down)
    select.select_by_value("")
    driver.find_element(By.ID, "modal_overlay").send_keys(Keys.PAGE_DOWN)
    time.sleep(3)
    ssid = driver.find_element(By.XPATH, "//div[@class ='cbi-value-field']/div[starts-with(@id, 'cbid.wireless.wifinet')]/input[@value ='OpenWrt']")
    ssid.clear()
    ssid.send_keys("😄😄😄😄")
    time.sleep(2)
    driver.find_element(By.XPATH, "//div[@class = 'cbi-value-field']/div/span[@class = 'more']").click()
    time.sleep(2)
    interface = driver.find_element(By.XPATH, "//div[@class = 'cbi-value-field cbi-dropdown-open']/div/ul/li[contains(@data-value, 'lan') and contains(@tabindex, '0')]/form/input[@type = 'checkbox']")
    action = ActionChains(driver)
    action.move_to_element(interface).click()
    time.sleep(2)
    action.perform()
    time.sleep(2)
    driver.find_element(By.XPATH, "//div/ul/li/a[contains(text(),'Wireless Security')]").click()
    time.sleep(2)
    wpa2 = Select(driver.find_element(By.XPATH, "//div[@class ='cbi-value-field']/div[starts-with(@id, 'cbid.wireless.wifinet') and contains(@id , 'encryption')]/select[starts-with(@id , 'widget.cbid.wireless.wifinet') and contains(@id , 'encryption')]"))
    wpa2.select_by_value("psk2")
    time.sleep(2)
    parent = driver.find_element(By.XPATH, "//div[@class= 'cbi-value-field']/div[starts-with(@id, 'cbid.wireless.wifinet') and contains(@id, '_wpa_key')]/input")
    parent.find_element(By.XPATH, "//input[starts-with(@id, 'widget.cbid.wireless.wifinet') and contains(@id, '_wpa_key') and contains(@class, 'cbi-input-password')]").send_keys('11112222')
    time.sleep(2)
    pmf_wpa2 = Select(driver.find_element(By.XPATH, "//div[@class = 'cbi-value-field']/div[contains(@id , 'ieee80211w') and starts-with(@id , 'cbid.wireless.wifinet')]/select[starts-with(@id , 'widget.cbid.wireless.wifinet') and contains(@id , 'ieee80211w')]"))
    pmf_wpa2.select_by_value("1")
    time.sleep(2)
    driver.find_element(By.XPATH, "//div[@id='modal_overlay']/div/div/button[contains(text(),'Save')]").click()
    print("Emoji Character profile created SSID : 😄😄😄😄")
    #final save and apply
    time.sleep(5)
    driver.find_element(By.XPATH, "//div[@id='view']/div/div/ul/li[contains(text(),'Save & Apply')]").click()
    time.sleep(2)


router = int(input("Please specify the router in use : linksys = 1 , Tp-Link = 2 \n"))
if router == 1:
    linksys()
elif router == 2:
    tp_link()




